# dispatch action to call a remote echo service
name: Run echo GHA from progress-platform-services/common-github-actions

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
      - develop
      - 'feature*'
      - 'releases/**'
    tags:
      - 'v*.*.*'
      - v1.**
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      foo:
          type: string
          default: 'bar'
           
jobs: 
  call-echo-service:
    #runs-on: ubuntu-latest
    #steps:
    #   - name: Call simple echo workflow
      uses: progress-platform-services/common-github-actions/.github/workflows/ci-echo-go.yml@main
      with:
        message: 'hello world'

  # CI-pipeline:
  #   uses: 'chef/common-github-actions/.github/workflows/ci-release-go-cli.yml@main'
  #   with:
  #     application-name: "arch-sample-cli"

  # Sonar:
  #   uses: 'chef/common-github-actions/.github/workflows/sonarqube.yml@main'
  #     secrets: inherit
           