on: 
    pull_request:
      types: [opened, synchronize, reopened, closed]
    push:
      branches:
        - main
        - develop
        - 'feature*'
        - 'releases/**'
      tags:
        - 'v*.*.*'
        - v1.**
    release:
      types: [published]

on:
    workflow_dispatch:
      inputs:
        foo:
           type: string
           default: 'bar'
           
  jobs:
   call-job:
     steps:
       - name: Call simple echo workflow
         uses: progress-platform-services/common-github-actions/.github/workflows/ci-echo-go.yml@main
         with:
           foo: 'hello world'