name: SonarQube scan

on:
  workflow_call:
    
jobs:
  echo_inputs:
    name: 'Echo pipeline stage'
    runs-on: ubuntu-latest
    steps:
    - name: Echo inputs
      run: |
        echo "Sonarqube scan for PRIVATE and INTERNAL repositories, running on ip-range-controlled runner"
    
  sonarqube:
    runs-on: ubuntu-latest-4-cores
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      # if: always()
      uses: sonarsource/sonarqube-scan-action@v5.0.0
      continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
