name: Trufflehog secret scan

on:
  workflow_call:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --json
        # --only-verified --fail --github-actions --results=verified,unknown --branch dev
        # TODO: use the GH_TOKEN --org=progress --token=ghp_xxxxx
      continue-on-error: false

    # TODO: if this is run on ad hoc workflow, we will scan all branches (need to pass in selected branch)

    # TODO: store the output somewhere
    # - name: Upload test coverage artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     # Name of the artifact to upload.
    #     # Optional. Default is 'artifact'
    #     name: test-coverage.out
    #     # A file, directory or wildcard pattern that describes what to upload
    #     path: test/unittest/coverage.out